// <auto-generated />
using System;
using DataAccess.Concrete.EntityfremeworkCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231124111840_InitialContext")]
    partial class InitialContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.Currency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Currencys");
                });

            modelBuilder.Entity("Entities.Concrete.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CriticalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShelfInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StockClassID")
                        .HasColumnType("int");

                    b.Property<int>("StockClassName")
                        .HasColumnType("int");

                    b.Property<int>("StockTypeID")
                        .HasColumnType("int");

                    b.Property<int>("StockTypeName")
                        .HasColumnType("int");

                    b.Property<int>("StockUnitID")
                        .HasColumnType("int");

                    b.Property<int>("StockUnitName")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StockClassID");

                    b.HasIndex("StockTypeID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Entities.Concrete.StockClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("StockClassName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StockClasss");
                });

            modelBuilder.Entity("Entities.Concrete.StockType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StockTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StockTypes");
                });

            modelBuilder.Entity("Entities.Concrete.StockUnit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AmountUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaperWeight")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PurchasePriceCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchasePriceCurrencyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalePriceCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalePriceCurrencyID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StockTypeID")
                        .HasColumnType("int");

                    b.Property<int>("StockTypeName")
                        .HasColumnType("int");

                    b.Property<long>("StockUnitCode")
                        .HasColumnType("bigint");

                    b.Property<int>("StockUnitName")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StockTypeID");

                    b.ToTable("StockUnits");
                });

            modelBuilder.Entity("Entities.Concrete.Stock", b =>
                {
                    b.HasOne("Entities.Concrete.StockClass", "StockClasss")
                        .WithMany("Stocks")
                        .HasForeignKey("StockClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.StockType", "StockTypes")
                        .WithMany("Stocks")
                        .HasForeignKey("StockTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockClasss");

                    b.Navigation("StockTypes");
                });

            modelBuilder.Entity("Entities.Concrete.StockUnit", b =>
                {
                    b.HasOne("Entities.Concrete.StockType", "StockTypes")
                        .WithMany("StockUnits")
                        .HasForeignKey("StockTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTypes");
                });

            modelBuilder.Entity("Entities.Concrete.StockClass", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Entities.Concrete.StockType", b =>
                {
                    b.Navigation("StockUnits");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
