// <auto-generated />
using System;
using DataAccess.Concrete.EntityfremeworkCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Concrete.Currency", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("ID");

                    b.ToTable("Currencys");
                });

            modelBuilder.Entity("Entities.Concrete.Stock", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CriticalAmount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ShelfInformation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<long>("StockClassID")
                        .HasColumnType("bigint");

                    b.Property<long>("StockTypeID")
                        .HasColumnType("bigint");

                    b.Property<long>("StockUnitID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ID");

                    b.HasIndex("RecordDate");

                    b.HasIndex("StockClassID");

                    b.HasIndex("StockTypeID");

                    b.HasIndex("StockUnitID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Entities.Concrete.StockClass", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("StockClassName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ID");

                    b.HasIndex("StockClassName");

                    b.ToTable("StockClasss");
                });

            modelBuilder.Entity("Entities.Concrete.StockType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StockTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ID");

                    b.HasIndex("StockTypeName");

                    b.ToTable("StockTypes");
                });

            modelBuilder.Entity("Entities.Concrete.StockUnit", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AmountUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<int>("PaperWeight")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal");

                    b.Property<long>("PurchasePriceCurrencyID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal");

                    b.Property<long>("SalePriceCurrencyID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<long>("StockTypeID")
                        .HasColumnType("bigint");

                    b.Property<long>("StockUnitCode")
                        .HasColumnType("bigint");

                    b.Property<string>("StockUnitName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ID");

                    b.HasIndex("StockTypeID");

                    b.HasIndex("StockUnitCode");

                    b.ToTable("StockUnits");
                });

            modelBuilder.Entity("Entities.Concrete.Stock", b =>
                {
                    b.HasOne("Entities.Concrete.StockClass", "StockClasss")
                        .WithMany("Stocks")
                        .HasForeignKey("StockClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.StockType", "StockTypes")
                        .WithMany("Stocks")
                        .HasForeignKey("StockTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.StockUnit", "StockUnits")
                        .WithMany("Stocks")
                        .HasForeignKey("StockUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockClasss");

                    b.Navigation("StockTypes");

                    b.Navigation("StockUnits");
                });

            modelBuilder.Entity("Entities.Concrete.StockUnit", b =>
                {
                    b.HasOne("Entities.Concrete.StockType", "StockTypes")
                        .WithMany("StockUnits")
                        .HasForeignKey("StockTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTypes");
                });

            modelBuilder.Entity("Entities.Concrete.StockClass", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Entities.Concrete.StockType", b =>
                {
                    b.Navigation("StockUnits");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Entities.Concrete.StockUnit", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
